version: "3.7"

services:
  bot:
    build: .
    command: python -u /app/main.py >> /app/db/log/activity.log 2>&1
    privileged: true
    volumes:
      - .:/app
    container_name: bot
    restart: always
    expose:
        - 5420
        - 5421
    environment:
      LISTEN_HOST: '0.0.0.0'
      INSIDE_DOCKER: 'true'
      SEND_HOST: web
      SEND_PORT: 5001
      SOCKET_HOST: socketapp
      SOCKET_PORT: 5001
  web:
    build: .
    command: uwsgi /app/app.ini
    privileged: true
    volumes:
      - .:/app
    container_name: web
    restart: always
    expose:
        - 5421
        - 5420
        - 5000
    ports:
      - "5000:5000"
    depends_on:
      - bot
    environment:
      PORT: 5000
      DEBUG: 'false'
      HOST: '0.0.0.0'
      SEND_HOST: bot
      INSIDE_DOCKER: 'true'
  socketapp:
    build: ./socket
    command: python -u /app/socket/socketapp.py >> /app/db/log/socket_activity.log 2>&1
    privileged: true
    volumes:
      - .:/app
    container_name: socketapp
    restart: always
    expose:
        - 5001
    ports:
        - "5001:5001"
    environment:
      PORT: 5001
      DEBUG: 'false'
      HOST: '0.0.0.0'
      INSIDE_DOCKER: 'true'
  nginx:
    image: nginx
    volumes:
      - ./db:/db
      - ./nginx.conf:/etc/nginx/nginx.conf
    container_name: nginx
    restart: always
    ports:
      - "5420:5420"
      - "80:80"
      - "443:443"
    depends_on:
      - web