services:
  bot:
    profiles:
      - bot
      - web
    build: .
    command: python -u /app/main.py >> /app/db/log/activity.log 2>&1
    privileged: true
    volumes:
      - .:/app
    container_name: bot
    restart: always
    expose:
        - 5421
    environment:
      LISTEN_HOST: '0.0.0.0'
      INSIDE_DOCKER: 'true'
      SOCKET_HOST: socketapp
      SOCKET_PORT: 5001
  web:
    profiles:
      - web
    build: .
    command: uwsgi /app/app.ini
    privileged: true
    volumes:
      - .:/app
    container_name: web
    restart: always
    expose:
      - 80
    depends_on:
      - bot
    environment:
      SEND_HOST: bot
      SEND_PORT: 5421
      SOCKET_HOST: '' # leave blank if you dont have a specific location of socketapp (server_location:5001) (home server = botsocket subdomain)
      DEBUG: 'false'
      INSIDE_DOCKER: 'true'
  socketapp:
    profiles:
      - web
    build: ./socket
    command: python -u /app/socket/socketapp.py >> /app/db/log/socket_activity.log 2>&1
    privileged: true
    volumes:
      - .:/app
    container_name: socketapp
    restart: always
    ports:
      - "5001:5001" # external:internal (home server = 27001 / botsocket subdomain)
    environment:
      PORT: 5001
      DEBUG: 'false'
      HOST: '0.0.0.0'
      INSIDE_DOCKER: 'true'
  nginx:
    image: nginx
    profiles:
      - web
    volumes:
      - ./db:/db
      - ./nginx.conf:/etc/nginx/nginx.conf
    container_name: nginx
    restart: always
    environment:
      WEB_HOST: web
      WEB_PORT: 80
    ports:
      - "80:80" # external:internal (home server = 27080 / botsocket subdomain)
      - "443:443" # external:internal (home server = 27443 / no ssl on botsocket subdomain)
    depends_on:
      - web