"""add heatmap

Revision ID: 1a355400242c
Revises: bbbcfd8e8176
Create Date: 2024-07-22 15:52:41.856785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a355400242c'
down_revision: Union[str, None] = 'bbbcfd8e8176'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('heatmap', sa.JSON(), nullable=True))
    op.add_column('now_playing', sa.Column('heatmap', sa.JSON(), nullable=True))
    op.add_column('queue', sa.Column('heatmap', sa.JSON(), nullable=True))
    op.add_column('save_videos', sa.Column('heatmap', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('save_videos', 'heatmap')
    op.drop_column('queue', 'heatmap')
    op.drop_column('now_playing', 'heatmap')
    op.drop_column('history', 'heatmap')
    # ### end Alembic commands ###
