"""new author

Revision ID: 3afd4693091a
Revises: 029ec03a366f
Create Date: 2024-03-23 10:27:43.018089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3afd4693091a'
down_revision: Union[str, None] = '029ec03a366f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.drop_column('history', 'author')
    op.drop_column('now_playing', 'author')
    op.drop_column('queue', 'author')
    op.drop_column('save_videos', 'author')

    op.add_column('history', sa.Column('author', sa.JSON(), nullable=True))
    op.add_column('now_playing', sa.Column('author', sa.JSON(), nullable=True))
    op.add_column('queue', sa.Column('author', sa.JSON(), nullable=True))
    op.add_column('save_videos', sa.Column('author', sa.JSON(), nullable=True))

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saves', sa.Column('author', sa.JSON(), nullable=True))
    op.drop_column('saves', 'author_name')
    op.drop_column('saves', 'author_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saves', sa.Column('author_id', sa.INTEGER(), nullable=True))
    op.add_column('saves', sa.Column('author_name', sa.VARCHAR(), nullable=True))
    op.drop_column('saves', 'author')
    op.alter_column('save_videos', 'author',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('queue', 'author',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('now_playing', 'author',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('history', 'author',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
