"""First revision

Revision ID: 9e2456acbb92
Revises: 
Create Date: 2024-01-07 18:33:48.661671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e2456acbb92'
down_revision: Union[str, None] = '356d7796aa6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guild_data', sa.Column('last_updated', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guild_data', 'last_updated')
    # ### end Alembic commands ###
