"""new last_updated

Revision ID: a63855c24f3e
Revises: 381a34760378
Create Date: 2024-03-13 00:21:17.188316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a63855c24f3e'
down_revision: Union[str, None] = '381a34760378'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guild_data', 'last_updated')
    op.add_column('guilds', sa.Column('last_updated', sa.JSON(), nullable=True))
    op.drop_column('options', 'last_updated')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('options', sa.Column('last_updated', sa.INTEGER(), nullable=True))
    op.drop_column('guilds', 'last_updated')
    op.add_column('guild_data', sa.Column('last_updated', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###


