"""removed search list

Revision ID: bc72923d75f8
Revises: 9e2456acbb92
Create Date: 2024-02-22 22:57:50.803736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'bc72923d75f8'
down_revision: Union[str, None] = '9e2456acbb92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search_list')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_list',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('position', sa.INTEGER(), nullable=True),
    sa.Column('class_type', sa.VARCHAR(), nullable=True),
    sa.Column('author', sa.VARCHAR(), nullable=True),
    sa.Column('guild_id', sa.INTEGER(), nullable=True),
    sa.Column('url', sa.VARCHAR(), nullable=True),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('picture', sa.VARCHAR(), nullable=True),
    sa.Column('duration', sa.VARCHAR(), nullable=True),
    sa.Column('channel_name', sa.VARCHAR(), nullable=True),
    sa.Column('channel_link', sa.VARCHAR(), nullable=True),
    sa.Column('radio_info', sqlite.JSON(), nullable=True),
    sa.Column('local_number', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.INTEGER(), nullable=True),
    sa.Column('played_duration', sqlite.JSON(), nullable=True),
    sa.Column('chapters', sqlite.JSON(), nullable=True),
    sa.Column('stream_url', sa.VARCHAR(), nullable=True),
    sa.Column('discord_channel', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
